"""empty message

Revision ID: b6aedad28bf5
Revises: cd47d7f92841
Create Date: 2020-12-01 01:48:50.216624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6aedad28bf5'
down_revision = 'cd47d7f92841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('categoria_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'categoria', ['categoria_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'categoria_id')
    # ### end Alembic commands ###
