"""empty message

Revision ID: cd47d7f92841
Revises: 
Create Date: 2020-12-01 00:07:58.261431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd47d7f92841'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('autor', sa.String(), nullable=True),
    sa.Column('ano', sa.String(), nullable=True),
    sa.Column('editora', sa.String(), nullable=True),
    sa.Column('pode_alugar', sa.Boolean(), nullable=True),
    sa.Column('alugado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tematicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tematica', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('titulos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('titulos')
    op.drop_table('tematicas')
    op.drop_table('categoria')
    op.drop_table('books')
    # ### end Alembic commands ###
