"""empty message

Revision ID: f527c3df4c25
Revises: b6aedad28bf5
Create Date: 2020-12-01 02:21:32.662697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f527c3df4c25'
down_revision = 'b6aedad28bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('tematica_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'tematicas', ['tematica_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'tematica_id')
    # ### end Alembic commands ###
